# -*- coding: utf-8 -*-
"""02_fin_modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTcYT2bWRE8HcIA9NQtBLBEaro4U2AnM
"""

import pandas as pd
import numpy as np

def load_processed_data(file_path='lotte_chilsung_financial_data.csv'):
    """Phase 1에서 저장한 데이터를 불러오는 함수"""
    df = pd.read_csv(file_path, index_with=0)
    return df

def calculate_reits_benefit(asset_value, cost_basis, tax_rate=0.2, discount_rate=0.05, years=5):
    """
    프로젝트 리츠 도입 시 세제 혜택 및 NPV 산출 로직
    - asset_value: 현재 유형자산 가치 (십억)
    - cost_basis: 취득원가 (가정치, 십억)
    - tax_rate: 법인세율 (기본 20%)
    - discount_rate: 할인율 (WACC 대용, 5%)
    - years: 과세 이연 기간 (보통 5년 이상)
    """
    # 1. 기존 PF 방식: 자산 매각/이전 시 양도세 즉시 발생
    capital_gain = asset_value - cost_basis
    immediate_tax = capital_gain * tax_rate

    # 2. 리츠 방식: 2026 세제개편안에 따른 과세 이연 (현물출자 특례)
    # 세금 납부 시점이 지연됨에 따른 화폐의 시간가치 이득(PV) 계산
    deferred_tax_pv = immediate_tax / ((1 + discount_rate) ** years)

    # 3. 재무적 이득 산출 (초기 현금유출 방어 및 재투자 기회비용)
    tax_saving_pv = immediate_tax - deferred_tax_pv

    return {
        'capital_gain': capital_gain,
        'immediate_tax': immediate_tax,
        'deferred_tax_pv': deferred_tax_pv,
        'net_benefit_pv': tax_saving_pv
    }

if __name__ == "__main__":
    # 실행 테스트 (Phase 1 실측 데이터 기준 예시)
    # 2024년 말 유형자산 약 2602.81 (십억)
    sample_asset = 2602.81
    sample_cost = 500.00 # 취득가 5천억 가정

    report = calculate_reits_benefit(sample_asset, sample_cost)

    print("--- Phase 2: 프로젝트 리츠 재무 모델링 결과 ---")
    print(f"1. 예상 양도차익: {report['capital_gain']:.2f} 십억")
    print(f"2. 기존 PF 방식 세금 (즉시 납부): {report['immediate_tax']:.2f} 십억")
    print(f"3. 리츠 방식 세금 (5년 이연 현재가치): {report['deferred_tax_pv']:.2f} 십억")
    print(f"4. 최종 재무적 이득 (세후 현금흐름 개선): {report['net_benefit_pv']:.2f} 십억")